mydisk/cat_disk/urls.py
from django.urls import path
from . import views


app_name = "cat_disk"

urlpatterns = [
    path("", views.index, name='index'),
    path("download/", views.download, name="download"),
]

mydisk/mydisk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cat_disk.urls'), name="disk"),
]

mydisk/cat_disk/views.py
import requests
import magic
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render


def check_disk(public_key):
    """Получение списка файлов и папок из публичной ссылки."""
    url = "https://cloud-api.yandex.net/v1/disk/public/resources"
    params = {
        "public_key": public_key
        }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        return response.json()
    return {"error": response.json().get("message", "Ошибка при доступе к Яндекс.Диску")}


def get_download_url(public_key, path=None):
    """Получение ссылки для скачивания файла."""
    url = "https://cloud-api.yandex.net/v1/disk/public/resources/download"
    params = {"public_key": public_key}
    if path:
        params["path"] = path
    response = requests.get(url, params=params)
    return response.json().get("href")


def index(request):
    """Отображение списка файлов."""
    if request.method == "POST":
        public_key = request.POST.get("public_key")
        files = check_disk(public_key)

        if "error" in files:
            messages.error(request, "Некорректная ссылка")
            return render(request, "disk/index.html", {"error": files["error"]})

        items = files.get("_embedded", {}).get("items", [])
        context = {
            "items": items, 
            "public_key": public_key
            }
        return render(request, "disk/public_disk.html", context)

    return render(request, "disk/index.html")


def download(request):
    """Скачивание файла."""
    public_key = request.GET.get("public_key")
    path = request.GET.get("path")

    download_url = get_download_url(public_key, path)
    response = requests.get(download_url)
    filename = path.split("/")[-1]

    magic_instance = magic.Magic(mime=True)
    mime_type = magic_instance.from_buffer(response.content)

    file_response = HttpResponse(response.content, content_type=mime_type)
    file_response["Content-Disposition"] = f'attachment; filename="{filename}"'
    return file_response

mydisk/templates/base.html
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>
			{% block title %} {{ title }} {% endblock %}
		</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
	</head>

	<body style="background-color: rgb(0, 0, 0);">
		{% include "includes/header.html" %}
		<main>
			{% if messages %} {% for message in messages %}
			<div
				class="alert alert-info"
				style="background-color: #000000; 
              border: none;
              padding: 10px 15px;
              border-radius: 10px;
              color: rgba(255, 255, 255, 0.568);
              font-weight: bolder;"
			>
				{{ message }}
			</div>
			{% endfor %} {% endif %}

			<div class="container py-5">
				{% block content %} {% endblock %}
			</div>
		</main>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
	</body>
</html>

mydisk/templates/disk/index.html
{% extends "base.html" %} {% block title %} Чек Я.Диск {% endblock %} {% block content %}
<div class="d-flex justify-content-center align-items-center vh-100 text-white">
	<div class="card bg-secondary shadow-lg border-0 p-4" style="max-width: 500px;">
		<h2 class="text-center mb-4" style="font-family: 'Segoe UI', sans-serif; font-weight: bold;">Просмотр <span style="color: rgb(146, 3, 3);">Я</span>.Диска</h2>
		<form method="POST">
			{% csrf_token %}
			<div class="mb-3">
				<label for="public_key" class="form-label fw-bold">Ссылка</label>
				<input type="text" id="public_key" name="public_key" class="form-control form-control-lg bg-dark text-white border-secondary" placeholder="Введите ссылку" required />
			</div>
			<div class="text-center">
				<button type="submit" class="btn btn-lg btn-dark w-100 fw-bold text-white border-secondary">
					Войти
				</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}

mydisk/templates/disk/public_disk.html
{% extends "base.html" %} {% block title %} Содержимое Яндекс.Диска {% endblock %} {% block content %}
<div class="container py-3">
	<h1 class="text-center mb-5 text-white" style="font-family: 'Segoe UI', sans-serif; font-weight: bold;">
		Содержимое папки
	</h1>
	<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-2">
		{% for item in items %}
		<div class="col">
			<div class="card text-white h-100 shadow-lg border" style="background-color: black;">
				<img src="{{ item.preview }}" class="card-img-top" style="height: 200px;" />
				<div class="card-body">
					<h5 class="card-title" style="color: gray;">{{ item.name }}</h5>
					{% if item.type == "file" %}
					<a href="{% url 'cat_disk:download' %}?public_key={{ public_key }}&path={{ item.path }}&name={{ item.name }}" class="btn w-100" style="color: rgba(255, 255, 255, 0.534);" download>Скачать</a>
					{% endif %}
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
	<div class="text-center mt-5">
		<a href="/" class="btn px-4 py-2" style="color: rgba(255, 255, 255, 0.534);">Назад</a>
	</div>
</div>
{% endblock %}

mydisk/templates/includes/header.html
<header class="text-white py-3 shadow">
	<div class="container d-flex justify-content-between align-items-center">
		<h1 class="fs-3 fst-italic">Чек <span style="color: rgb(146, 3, 3);">Я</span>.Диск</h1>
		<nav>
			<a href="/" class="btn me-2">Главная</a>
		</nav>
	</div>
	<hr />
</header>

  